### ISSUE TITLE
Leaderboard not showing everyone

### ISSUE THREAD

**Issue by mobilegmYT** [cryx3001/Stock-Market-Discord-Bot#15]
**Describe the bug**
When it shows the leaderboard, sometimes it doesn't show everyone and says that some people might be missing. There are a total of 8 people in the database for the server. This seems to happen after a period of inactivity where people don't use the bot after a while, then only people who interact with it get displayed. 

e.g: I ran the leaderboard and it only showed me. Then someone interacted with the bot, and now they get displayed on it too, but no one else in the database is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/44128563/118370596-8dc8bf00-b565-11eb-9392-e0a9bdd58b20.png)
![image](https://user-images.githubusercontent.com/44128563/118370621-b9e44000-b565-11eb-813d-d754eff66040.png)

**Additional context**
This is an instance of the bot I'm running myself, but there aren't any changes to the code related to the leaderboard.

And also I'm using the mysql database hosting from alwaysdata, like I was told to

**Comment by sriyansgamer** [comment]
I remember Cryx saying that it's a problem with caching or something. I know that there are only 8 people in your server but I think he needs some permissions from Discord themselves regarding the bot. I think it would be helpful if @cryx3001 can give a more informed and official response.

**Comment by mobilegmYT** [comment]
> I remember Cryx saying that it's a problem with caching or something. I know that there are only 8 people in your server but I think he needs some permissions from Discord themselves regarding the bot. I think it would be helpful if @cryx3001 can give a more informed and official response.

Actually another issue is that there are more than 8 people, but when another person tries to make a account after the database already has 8 people, it gets stuck here
![image](https://user-images.githubusercontent.com/44128563/118528517-ae2c8100-b6ff-11eb-9b5e-ebe1bfe5fdc5.png)

**Comment by cryx3001** [comment]
For the leaderboard, I need special permissions given by Discord. For now, they don't want to give these permissions to me.

> Actually another issue is that there are more than 8 people, but when another person tries to make a account after the database already has 8 people, it gets stuck here
> ![image](https://user-images.githubusercontent.com/44128563/118528517-ae2c8100-b6ff-11eb-9b5e-ebe1bfe5fdc5.png)

I have never seen this bug, and I'm unable to reproduce it, maybe an issue with your database, I don't really know 🤷🏼‍♂️

**Comment by mobilegmYT** [comment]
> For the leaderboard, I need special permissions given by Discord. For now, they don't want to give these permissions to me.
> 
> > Actually another issue is that there are more than 8 people, but when another person tries to make a account after the database already has 8 people, it gets stuck here
> > ![image](https://user-images.githubusercontent.com/44128563/118528517-ae2c8100-b6ff-11eb-9b5e-ebe1bfe5fdc5.png)
> 
> I have never seen this bug, and I'm unable to reproduce it, maybe an issue with your database, I don't really know 🤷🏼‍♂️

I'm using the alwaysdata DB hosting you mentioned in the README. So far, I can't find any other free DB hostings that work since though, as when I change the db stuff in config to them, I get:
![image](https://user-images.githubusercontent.com/44128563/118530438-e6cd5a00-b701-11eb-909c-e5fe77ea7670.png)

Perhaps maybe you could add a way to make the bot use sqlite instead of mysql so no server stuff is needed?

**Comment by cryx3001** [comment]
The next version of the bot will use MongoDB.
